resources:
  - url: /fluvalble/fluvalble-schedule-card.js
    type: module

views:
  - title: Aquarium
    path: aquarium
    cards:
      - type: custom:fluvalble-effect-schedule-card
        title: Fluval Timed Effects

      - type: custom:fluvalble-schedule-card
        title: AquaSky 24 Hour Schedule
        physical_preview: true
        preview_duration: 60
        step_seconds: 2
        points:
          - time: "00:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "10:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "11:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "16:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "19:00"
            channel_1: 3
            channel_2: 0
            channel_3: 8
            channel_4: 0
          - time: "20:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
      - type: custom:fluvalble-spectrum-card
        title: AquaSky Spectrum Bars
        points:
          - time: "00:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "10:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "11:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "16:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "19:00"
            channel_1: 3
            channel_2: 0
            channel_3: 8
            channel_4: 0
          - time: "20:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
      - type: custom:fluvalble-wavelength-card
        title: AquaSky Wavelength Preview
        points:
          - time: "00:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "10:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
          - time: "11:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "16:00"
            channel_1: 10
            channel_2: 10
            channel_3: 25
            channel_4: 5
          - time: "19:00"
            channel_1: 3
            channel_2: 0
            channel_3: 8
            channel_4: 0
          - time: "20:00"
            channel_1: 0
            channel_2: 0
            channel_3: 0
            channel_4: 0
