resources:
  - url: /fluvalble/fluvalble-schedule-card.js
    type: module

views:
  - title: Aquarium
    path: aquarium
    cards:
      - type: custom:fluvalble-effect-schedule-card
        title: Fluval Timed Effects

      - type: custom:fluvalble-schedule-card
        title: AquaSky 24 Hour Schedule
        physical_preview: true
        preview_duration: 60
        step_seconds: 2
        points:
          - time: "00:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "10:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "11:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "16:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "19:00"
            red: 3
            green: 0
            blue: 8
            white: 0
          - time: "20:00"
            red: 0
            green: 0
            blue: 0
            white: 0
      - type: custom:fluvalble-spectrum-card
        title: AquaSky Spectrum Bars
        points:
          - time: "00:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "10:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "11:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "16:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "19:00"
            red: 3
            green: 0
            blue: 8
            white: 0
          - time: "20:00"
            red: 0
            green: 0
            blue: 0
            white: 0
      - type: custom:fluvalble-wavelength-card
        title: AquaSky Wavelength Preview
        points:
          - time: "00:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "10:00"
            red: 0
            green: 0
            blue: 0
            white: 0
          - time: "11:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "16:00"
            red: 10
            green: 10
            blue: 25
            white: 5
          - time: "19:00"
            red: 3
            green: 0
            blue: 8
            white: 0
          - time: "20:00"
            red: 0
            green: 0
            blue: 0
            white: 0
